// Semantic (L4) evidence manifest, increments 1 (if, do, condition lists, the default envelope),
// 2 (switch, switch-scoped break, exit), 3 (while, repeat, for, each, loop-scoped break) and
// 4 (on, every, the tep/tsp/tcp task policy vocabularies).
//
// A claim states what a saved construct means at runtime, never a live outcome. It is promoted only
// when L4Promotion finds every contract item: the structure it rests on is L3, a documentation
// disposition, hashed pinned-source regions equal to the registry, a canonical fixture with its
// save in the committed lineage, a hand-authored trace that reaches it, a traced edge occurrence and
// a named nearest misreading. Source drift in a cited region withdraws only the claims citing it.
// Everything a claim does not cover is an occurrence-scoped gap from the closed list below.
[
  provenance: [
    commit: '0a37eee2537accd706aaaeeed5a7b4bb0c82646e',
    registry: 'tools/webcore-investigation/generated/webcore_construct_registry.groovy',
    structuralEvidence: 'tools/webcore-investigation/evidence/statement-l3.groovy'
  ],
  contract: ['structural-l3', 'documentation-disposition', 'hashed-source-regions', 'canonical-fixture-lineage',
             'hand-authored-trace', 'traced-edge-occurrence', 'named-negative'],
  traceDirectory: 'tests/fixtures/webcore-l4/traces',

  claims: [
    [id: 'statement.if.branch-order.v1', structural: ['wc.statement.if'],
     meaning: 'An if takes then when its condition list holds, otherwise tests each else-if in saved order, and takes else only when none matched.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'Documents the If Block as the statement for checking conditions; the else-if order is undocumented, source only']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-01-conditional.edit-round-trip'],
     edges: [[fixture: 'l3-01-conditional.edit-round-trip', path: '$.s[1]', exercises: 'an if with no else-if and no else']],
     negative: 'else-if branches are unordered or evaluated together'],

    [id: 'condition.list.negation.v1', structural: ['wc.statement.if'],
     meaning: 'A condition list or group with n true inverts its combined result; without n it does not.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'Documents condition groups; negation is undocumented, source only']],
     sources: [[region: 'executor.evaluate-conditions', sha256: '6972420b01a18e8ee17a2c727fedf6852bc3ae56ff66879d4accc932a6b280ca']],
     fixtures: ['l3-01-conditional.edit-round-trip'],
     edges: [[fixture: 'l3-02-followed-by.edit-round-trip', path: '$.s[1]', exercises: 'a group without negation']],
     negative: 'a negated condition list is read as not negated'],

    [id: 'condition.list.operator-or.v1', structural: ['wc.statement.if'],
     meaning: 'A condition list or group whose operator is or holds when any of its ordered children holds.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'Documents a condition group as conditions joined by a logical operator such as and, or, xor']],
     sources: [[region: 'executor.evaluate-conditions', sha256: '6972420b01a18e8ee17a2c727fedf6852bc3ae56ff66879d4accc932a6b280ca']],
     fixtures: ['l3-01-conditional.edit-round-trip'],
     edges: [[fixture: 'l3-01-conditional.edit-round-trip', path: '$.s[1]', exercises: 'operators the fixtures do not prove']],
     negative: 'an unproven operator such as and is read as or'],

    [id: 'condition.followed-by.opaque-group.v1', structural: ['wc.statement.if'],
     meaning: 'A group whose operator is followed by is a timed sequence of events, kept opaque, never a boolean and.',
     docs: [[page: 'https://community.webcore.co/t/if-this-then-wait-then-if/1393', disposition: 'Community guidance uses followed by for a sequence of events over time'],
            [page: 'https://community.webcore.co/t/sequence-of-events/5037', disposition: 'Community guidance uses followed by to detect an ordered sequence of events']],
     sources: [[region: 'executor.evaluate-conditions', sha256: '6972420b01a18e8ee17a2c727fedf6852bc3ae56ff66879d4accc932a6b280ca']],
     fixtures: ['l3-02-followed-by.edit-round-trip'],
     edges: [[fixture: 'l3-02-followed-by.edit-round-trip', path: '$.s[1]', exercises: 'an ordinary group beside a followed-by group']],
     negative: 'a followed-by group is read as an ordinary boolean and group'],

    [id: 'statement.do.sequential-block.v1', structural: ['wc.statement.do'],
     meaning: 'A do executes its saved child statements once, in order, and lowers the statement level while they run.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'Documents Do as a construct for grouping other statements together; its statement-level effect is undocumented, source only']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-04-loops.edit-round-trip'],
     edges: [[fixture: 'l3-04-loops.edit-round-trip', path: '$.s[0]', exercises: 'a loop containing the do']],
     negative: 'do is read as a loop or as transparent to statement level'],

    [id: 'statement.envelope.default.v1', structural: ['wc.statement.if', 'wc.statement.action'],
     meaning: 'A statement with no restrictions, synchronous a, no task execution or scheduling policy and saved tcp c runs with the default envelope.',
     docs: [[page: 'https://wiki.webcore.co/Execution_Method', disposition: 'Documents synchronous execution as the normal default'],
            [page: 'https://wiki.webcore.co/Task_Cancellation_Policy', disposition: 'Documents the cancellation policy; saved c as the default comes from the pinned editor and executor']],
     sources: [[region: 'executor.clean-code', sha256: '4522bc571384d95ee726e3e8a0b2fcad2a99553a96e866614e50e5515dc250e2']],
     fixtures: ['l3-01-conditional.edit-round-trip'],
     edges: [[fixture: 'l3-08-policies.round-trip', path: '$.s[0]', exercises: 'restrictions and explicit policies'],
             [fixture: 'l3-08-policies.round-trip', path: '$.s[2]', exercises: 'an execution policy with the default tcp']],
     negative: 'a saved absent tcp, which is never cancel, is read as the default'],

    [id: 'statement.switch.ordered-cases.v1', structural: ['wc.statement.switch'],
     meaning: 'A switch tries each case in saved order against a single-value or range comparison, kept opaque. Ctp absent or i stops scanning after the first match; ctp e continues to later cases and the default until a break is reached.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'The Piston page links to a Switch construct page that is empty; case order and the ctp fall-through rule are undocumented, source only']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-03-switch.edit-round-trip'],
     edges: [[fixture: 'l3-03-switch.edit-round-trip', path: '$.s[1]', exercises: 'ctp i with one case and no default']],
     negative: 'every case is tried regardless of ctp, so fall-through and auto-break read the same'],

    [id: 'statement.switch.default.v1', structural: ['wc.statement.switch'],
     meaning: 'A switch default section, when saved, is eligible to run only when no case matched, or in fall-through mode when no break interrupted case execution first.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'Undocumented, source only: the Switch construct page is empty']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-03-switch.edit-round-trip'],
     edges: [[fixture: 'l3-03-switch.edit-round-trip', path: '$.s[0]', exercises: 'a default section guarded by a break inside the matching case']],
     negative: 'the default section always runs after the case list, whether or not a case matched or broke'],

    [id: 'statement.break.switch-scope.v1', structural: ['wc.statement.break', 'wc.statement.switch'],
     meaning: 'A break saved directly in a switch case or default statement list, with no loop between them, stops that switch: it suppresses the default section and execution continues after the switch.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'Undocumented, source only: the Break construct page is empty']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-03-switch.edit-round-trip'],
     edges: [[fixture: 'l3-03-switch.edit-round-trip', path: '$.s[0].cs[0].s[1]', exercises: 'a break whose nearest container is a switch']],
     negative: 'a break inside a switch case terminates the whole piston, as exit does'],

    [id: 'statement.exit.terminate-piston.v1', structural: ['wc.statement.exit'],
     meaning: 'An exit statement, when the piston is running normally, terminates the whole piston: every enclosing container stops. Its operand supplies the exit state and is kept opaque.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'Undocumented, source only: the Exit construct page is empty']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-05-iteration.edit-round-trip'],
     edges: [[fixture: 'l3-05-iteration.edit-round-trip', path: '$.s[2]', exercises: 'an exit nested inside no loop or switch']],
     negative: 'exit only exits its immediate containing statement, the way break does'],

    [id: 'statement.while.pre-condition-loop.v1', structural: ['wc.statement.while'],
     meaning: 'A while evaluates its condition list before each pass; the body runs, and the loop repeats, only while the condition holds. It runs zero or more times.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'The Piston page links to a While Loop construct page that is empty; the pre-condition, zero-or-more-times rule is undocumented, source only']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-04-loops.edit-round-trip'],
     edges: [[fixture: 'l3-04-loops.edit-round-trip', path: '$.s[1]', exercises: 'a while with an unnegated condition']],
     negative: 'a while runs its body once unconditionally before checking the condition, the way repeat does'],

    [id: 'statement.repeat.post-condition-loop.v1', structural: ['wc.statement.repeat'],
     meaning: 'A repeat runs its body first, then evaluates its condition list; it repeats only while the condition does not yet hold, so it stops once the condition becomes true. It runs at least once.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'The Piston page links to a Repeat construct page that is empty; the post-condition, stop-on-true rule is undocumented, source only']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-04-loops.edit-round-trip'],
     edges: [[fixture: 'l3-04-loops.edit-round-trip', path: '$.s[3]', exercises: 'a repeat with an unnegated condition']],
     negative: 'a repeat continues running while its condition holds, the same as while'],

    [id: 'statement.for.step-iteration.v1', structural: ['wc.statement.for'],
     meaning: 'A for runs its body once per step from a saved start operand to a saved end operand by a saved step operand, in order. The operand values themselves are kept opaque.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'The Piston page links to a For Loop construct page that is empty; undocumented, source only']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-05-iteration.edit-round-trip'],
     edges: [[fixture: 'l3-05-iteration.edit-round-trip', path: '$.s[0]', exercises: 'a for with a saved counter variable']],
     negative: 'a for runs its body exactly once, ignoring its start, end and step operands'],

    [id: 'statement.each.device-iteration.v1', structural: ['wc.statement.each'],
     meaning: 'An each runs its body once per device in its saved device-list operand, in the saved device order. The operand itself is kept opaque.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'The Piston page links to a For Each Loop construct page that is empty; undocumented, source only']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-05-iteration.edit-round-trip'],
     edges: [[fixture: 'l3-05-iteration.edit-round-trip', path: '$.s[1]', exercises: 'an each with a saved counter variable']],
     negative: 'an each runs its body exactly once, ignoring the device list it saves'],

    [id: 'statement.break.loop-scope.v1', structural: ['wc.statement.break', 'wc.statement.while', 'wc.statement.repeat', 'wc.statement.for', 'wc.statement.each'],
     meaning: 'A break saved directly in a while, repeat, for or each own statement list, with no further nesting, stops that loop: the loop does not repeat, and execution continues after it.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'Undocumented, source only: the Break construct page is empty']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-04-loops.edit-round-trip'],
     edges: [[fixture: 'l3-04-loops.edit-round-trip', path: '$.s[0].s[2]', exercises: 'a break whose nearest container is a while, alongside a nested do']],
     negative: 'a break inside a loop terminates the whole piston, as exit does'],

    [id: 'statement.on.any-event-match.v1', structural: ['wc.statement.on'],
     meaning: 'An on statement runs its body when any of its saved event matchers matches the event that triggered this execution; matching against the trigger itself is kept opaque.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'Undocumented, source only: the On construct page is empty']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-07-events.edit-round-trip'],
     edges: [[fixture: 'l3-07-events.edit-round-trip', path: '$.s[0]', exercises: 'an on with two saved event matchers']],
     negative: 'an on requires every saved event matcher to match, rather than any one of them'],

    [id: 'statement.every.own-timer-only.v1', structural: ['wc.statement.every'],
     meaning: 'An every statement runs its body only when its own scheduled timer event fires, never on any other trigger, and every occurrence of its own timer event, whether or not restrictions allowed the body to run, terminates the whole piston execution pass: no statement saved after it in the same execution runs.',
     docs: [[page: 'https://wiki.webcore.co/Piston', disposition: 'Undocumented, source only: the Every construct page is empty']],
     sources: [[region: 'executor.statement-dispatch', sha256: 'a9eb246dda94cdd5d03d246ba51cd89d5c7e628f57b9d9fdaac88190c95cd643']],
     fixtures: ['l3-06-timers.round-trip'],
     edges: [[fixture: 'l3-06-timers.round-trip', path: '$.s[1]', exercises: 'a second every statement, unreachable if the first already terminated the pass']],
     negative: 'an every continues to its following siblings after its own timer fires, the way an ordinary statement does'],

    [id: 'statement.tep.execution-policy.v1', structural: ['wc.statement.action'],
     meaning: 'A saved tep governs whether a statement re-executes its tasks on every trigger: absent means always, c means only on condition-state change, p means only on piston-state change, b means either.',
     docs: [[page: 'https://wiki.webcore.co/Task_Execution_Policy', disposition: 'Documents all four options and that no limit, the default, always executes']],
     sources: [[region: 'executor.execute-action', sha256: '49f61a9b3c3567a9e92772e550541824192d6b36268303b8ca99a0c4846aa9b4']],
     fixtures: ['l3-08-policies.round-trip'],
     edges: [[fixture: 'l3-08-policies.round-trip', path: '$.s[0]', exercises: 'a saved tep of c']],
     negative: 'an absent tep is read as never executing the tasks, rather than always'],

    [id: 'statement.tsp.scheduling-policy.v1', structural: ['wc.statement.action'],
     meaning: 'A saved tsp governs a new delayed task schedule for the same action: absent drops the earlier pending schedule and replaces it, a keeps the earlier one and adds the new schedule alongside it.',
     docs: [[page: 'https://wiki.webcore.co/Task_Scheduling_Policy', disposition: 'Documents override (the default) versus allow multiple scheduled tasks']],
     sources: [[region: 'executor.schedule-timer', sha256: '15b08d2aa476d10c17659bf0914bba738d1556aef4374054849140ea66f43d6e']],
     fixtures: ['l3-08-policies.round-trip'],
     edges: [[fixture: 'l3-08-policies.round-trip', path: '$.s[0]', exercises: 'a saved tsp of a']],
     negative: 'a saved tsp of a is read as override, dropping the earlier schedule, rather than allowing both'],

    [id: 'statement.tcp.cancellation-policy.v1', structural: ['wc.statement.action'],
     meaning: 'A saved tcp governs whether a pending delayed task is cancelled when its condition or piston state changes: absent means never cancel, c cancels on condition-state change and is the documented default, p cancels on piston-state change, b cancels on either.',
     docs: [[page: 'https://wiki.webcore.co/Task_Cancellation_Policy', disposition: 'Documents all four options and states that cancel on condition-state change is the default']],
     sources: [[region: 'executor.clean-code', sha256: '4522bc571384d95ee726e3e8a0b2fcad2a99553a96e866614e50e5515dc250e2']],
     fixtures: ['l3-08-policies.round-trip'],
     edges: [[fixture: 'l3-08-policies.round-trip', path: '$.s[1]', exercises: 'a saved tcp of p']],
     negative: 'a saved tcp of c is read as never cancel']
  ],

  // Named misreadings for the recorded limits. They cap occurrences and are never promoted.
  limits: [
    [gap: 'statement.if.automatic-piston-state-unresolved', negative: 'if has no side effect beyond branch selection', source: 'executor.statement-dispatch'],
    [gap: 'condition.leaf-opaque', negative: 'a saved ct decides a condition leaf role', source: 'executor.evaluate-conditions'],
    [gap: 'statement.break.container-unresolved', negative: 'a break with neither a switch nor a loop as its nearest container is read as scoped to one anyway', source: 'executor.statement-dispatch']
  ],

  gaps: [
    'statement.envelope.restrictions-present': 'Restrictions gate this statement and their meaning is not yet proven',
    'statement.envelope.async': 'The execution method is not the proven synchronous default',
    'statement.envelope.tep-present': 'A task execution policy is set and its meaning is not yet proven',
    'statement.envelope.tsp-present': 'A task scheduling policy is set and its meaning is not yet proven',
    'statement.envelope.tcp-non-default': 'The task cancellation policy is not the proven default',
    'statement.if.automatic-piston-state-unresolved': 'A top-level if may set the automatic piston state, which is not yet explained',
    'statement.if.fast-forward-resumption-unresolved': 'Resumed execution may enter a branch regardless of the condition, which is not yet explained',
    'statement.action.not-in-increment': 'The meaning of this statement type is not yet proven',
    'statement.unrecognised': 'The statement type is not recognised',
    'condition.leaf-opaque': 'A condition comparison is shown as opaque until its meaning is proven',
    'condition.operator-unproven': 'This condition operator is not yet proven',
    'condition.group-depth-unproven': 'A group inside a group is not yet proven',
    'condition.followed-by-timing-unproven': 'The timing of a followed-by sequence is not yet explained',
    'statement.switch.fast-forward-unresolved': 'Resumed execution may behave differently from a normal run, which is not yet explained',
    'statement.break.fast-forward-unresolved': 'Resumed execution may behave differently from a normal run, which is not yet explained',
    'statement.break.container-unresolved': 'This break statement is not directly inside a switch case or default, so its scope is not yet proven',
    'statement.exit.fast-forward-unresolved': 'Resumed execution may behave differently from a normal run, which is not yet explained',
    'statement.while.fast-forward-unresolved': 'Resumed execution may behave differently from a normal run, which is not yet explained',
    'statement.repeat.fast-forward-unresolved': 'Resumed execution may behave differently from a normal run, which is not yet explained',
    'statement.for.fast-forward-unresolved': 'Resumed execution may behave differently from a normal run, which is not yet explained',
    'statement.each.fast-forward-unresolved': 'Resumed execution may behave differently from a normal run, which is not yet explained',
    'statement.on.fast-forward-unresolved': 'Resumed execution may behave differently from a normal run, which is not yet explained',
    'statement.every.fast-forward-unresolved': 'Resumed execution may behave differently from a normal run, which is not yet explained',
    'claim.statement.if.branch-order.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.condition.list.negation.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.condition.list.operator-or.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.condition.followed-by.opaque-group.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.do.sequential-block.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.envelope.default.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.switch.ordered-cases.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.switch.default.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.break.switch-scope.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.exit.terminate-piston.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.while.pre-condition-loop.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.repeat.post-condition-loop.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.for.step-iteration.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.each.device-iteration.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.break.loop-scope.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.on.any-event-match.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.every.own-timer-only.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.tep.execution-policy.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.tsp.scheduling-policy.v1.not-promoted': 'This claim lost its evidence, for example after source drift',
    'claim.statement.tcp.cancellation-policy.v1.not-promoted': 'This claim lost its evidence, for example after source drift'
  ]
]
